name: Optimizer Bot

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run optimizer
        env:
          OPTIMIZER_PAT: ${{ secrets.OPTIMIZER_PAT }}
          GITHUB_REPO: ${{ github.repository }}
        run: node tools/optimizer.js
